export const SET_BRANCHES = 'SET_BRANCHES'
export const ADD_BRANCH = 'ADD_BRANCH'
export const SET_CLUBS = 'SET_CLUBS'
export const DELETE_CLUB = 'DELETE_CLUB'
export const SET_CCOMPANY = 'SET_CCOMPANY'
export const DELETE_CCOMPANY = 'DELETE_CCOMPANY'
export const DELETE_VENDOR = 'DELETE_VENDOR'
export const SET_VENDOR = 'SET_VENDOR'
export const SET_OFFER = 'SET_OFFER'
export const SET_ALERT = 'SET_ALERT'
export const DELETE_ALERT = 'DELETE_ALERT'
export const DELETE_OFFER = 'DELETE_OFFER'
export const SET_ALL_VENDOR = 'SET_ALL_VENDOR'
export const DELETE_ALL_VENDOR = 'DELETE_ALL_VENDOR'
export const SET_ALL_CLUB = 'SET_ALL_CLUB'
export const DELETE_ALL_CLUB = 'DELETE_ALL_CLUB'
export const TOTAL_COMPANY = 'TOTAL_COMPANY'
export const TOTAL_VENDOR = 'TOTAL_VENDOR'
export const TOTAL_CLUB = 'TOTAL_CLUB'

export default {
    SET_BRANCHES,
    ADD_BRANCH,
    SET_CLUBS,
    DELETE_CLUB,
    SET_CCOMPANY,
    DELETE_CCOMPANY,
    DELETE_VENDOR,
    SET_VENDOR,
    SET_OFFER,
    SET_ALERT,
    DELETE_OFFER,
    DELETE_ALERT,
    SET_ALL_VENDOR,
    SET_ALL_CLUB,
    DELETE_ALL_CLUB,
    DELETE_ALL_VENDOR,
    TOTAL_COMPANY,
    TOTAL_VENDOR,
    TOTAL_CLUB,
}